# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.runs/synth_1/mmp_iddmm_sp.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.maxThreads 8
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu5ev-sfvc784-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.cache/wt [current_project]
set_property parent.project_path E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo e:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/x.mem
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/m.mem
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/y.mem
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/a0.mem
}
read_verilog -library xil_defaultlib {
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/mm_iddmm_sub.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/mmp_iddmm_addend.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/mmp_iddmm_addfirst.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/mmp_iddmm_ctrl.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/mmp_iddmm_mul128.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/mmp_iddmm_pe.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/mmp_iddmm_shift.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/common/mult.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/common/simple_p12adder256_3_2.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/common/simple_p1adder129.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/common/simple_ram.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/common/simple_vedic_128bit.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/common/simple_vedic_16bit.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/common/simple_vedic_32bit.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/common/simple_vedic_4bit.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/common/simple_vedic_64bit.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/common/simple_vedic_8bit.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/mmp_iddmm_sp.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/mmp_iddmm_top.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/mm_r2mm.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/mm_r2mm_2n.v
  E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/sources_1/new/me_top.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/constrs_1/new/mm_r2mm.xdc
set_property used_in_implementation false [get_files E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/constrs_1/new/mm_r2mm.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/github/school/RSA2048/vivado-mmp/RSA2048/RSA2048.srcs/utils_1/imports/synth_1/mmp_iddmm_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mmp_iddmm_sp -part xczu5ev-sfvc784-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mmp_iddmm_sp.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mmp_iddmm_sp_utilization_synth.rpt -pb mmp_iddmm_sp_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
